### ISSUE TITLE
Section Partial Least Squares: num_comp seems to be not tunable in {r chapter-06-pcr} and {r chapter-06-pls}

### ISSUE THREAD

**Issue by marcellodegiosa** [topepo/tidyAPM#1]

**Comment by topepo** [comment]
I don't any issues with this; can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by marcellodegiosa** [comment]
I'm working on a  downloaded  "tidyAPM" on my desktop.
I faced several issues when running chunks in "chapter-06-Rmd" one at a time.
Let's start from the very first one (chunk "chapter-06-fig-03").

So:
- if I first run "_common.R", and then the chunks in "chapter-06-Rmd" one at a time, when running chunk "chapter-06-fig-03" I get this error:
![Yes  _common R](https://user-images.githubusercontent.com/43028294/106267926-a917f480-622a-11eb-9ae7-0c444a7df64f.png)
If I don'run "_common.R" I get this one:
![No  _common R](https://user-images.githubusercontent.com/43028294/106267972-b9c86a80-622a-11eb-98a6-d7e93608ffcd.png)

Sorry for the screenshot. I hope they may help.

MDG

**Comment by marcellodegiosa** [comment]
With updated version of "recipes" it is working now.

MDG
