### ISSUE TITLE
Can't find "all_numeric_predictors" function, when running chunks in "chapter-03-Rmd"

### ISSUE THREAD

**Issue by marcellodegiosa** [topepo/tidyAPM#3]
Hi,

I have run (after "_common.R") the chunks in chapter-03-Rmd one at a time.

When running {r chapter-03-center-scale-prep} I got an error.
It seems that function "all_numeric_predictors" cannot be found.

I hope the screenshot below may help

![Schermata 2021-01-29 alle 11 18 20](https://user-images.githubusercontent.com/43028294/106262774-c2697280-6223-11eb-87f1-0b38e2845ff7.png)

The same issue happens when I run "index.Rmd" in a downloaded "tidyAPM" on my Desktop.

![Schermata 2021-01-29 alle 11 31 38](https://user-images.githubusercontent.com/43028294/106264158-9818b480-6225-11eb-8696-f10b655d3103.png)
 
Sorry for the screenshot. I was not able to reproduce the issue in a readable way with `reprex()`

I'm running code on RStudio Desktop.

Regards

MDG

**Comment by topepo** [comment]
The wrong version of `recipes` is installed. Since there is a description file, you should load the appropriate packages using `devtools::install()` from the root directory of the project. 

I'll update the readme to reflect this. 

Keep in mind that this book is changing a lot as I develop it and will, for now, depend on development versions of a number of packages.

**Comment by marcellodegiosa** [comment]
Thanks.
It works now.

MDG
